### ISSUE TITLE
[BUG] This error pops up

### ISSUE THREAD

**Issue by Matias-N5** [openai/gpt-discord-bot#54]
Im using replit
![image](https://user-images.githubusercontent.com/117122048/224395600-cbf5c2ae-0338-4d45-8ddb-333b18673871.png)
Solve my problem pls

**Comment by 1wdcgyjm-4415** [comment]
i am sorry i can't help you

**Comment by nooksmr** [comment]
First at all, pls remove .example
Second at all, don't show your Discord Token like that. Please, reset it.

**Comment by DaSkoolMan** [comment]
That's because you are not following the instructions. This is not a bug. Second of all, reset your token as you showed it to the public.

**Comment by Mohdjariullah** [comment]
@MatiasFlipper Try resetting Token again and again, this removes the invalid items in value, i too got this error, i resolved  it like this :)

**Comment by akn714** [comment]
Happy to help!, 
I also sometimes use replit,
This is a new feature of replit in which you can't make a `.env` file else there is a new option in the side panel named `secrets`.
In the `secrets` tab you can store your keys, replit does not allow you to make `.env` file now.

You were not able to make a `.env` file, I thik that's why you created `.env.example` file

**Comment by Kav-K** [comment]
Your environment file needs to be named `.env`
