### ISSUE TITLE
How to support non-chatGPT message/reply ?

### ISSUE THREAD

**Issue by rcholic** [openai/gpt-discord-bot#69]
With the awesome code here, my discord now supports interaction with ChatGPT; however, I also want to support some custom bot commands that do not require ChatGPT interaction.

I've tried to intercept the command/message inside the `on_message` method in **main.py** by using `bot.process_commands(message)`, but it does stop the bot from interacting with ChatGPT:

```
bot = commands.Bot(command_prefix='!', intents=intents, help_command=help_command)
@bot.command(name='hello', help='Send Hello')
async def say_hello(ctx):
    await emb.send_embed(ctx, title='Hello World')

@client.event
async def on_message(message: DiscordMessage):
    try:
        # block servers not in allow list
        bot.process_commands(message)
        if should_block(guild=message.guild):
            return
  ....
```

So is it even possible to have custom commands along with ChatGPT interactions? Thanks

**Comment by iN-T0k** [comment]
!chat

**Comment by iN-T0k** [comment]
!chat

**Comment by Kav-K** [comment]
Hey, the ChatGPT interactions are still going through because there is a separate on_message that fires here: https://github.com/Kav-K/gpt-discord-bot-1/blob/13e6b70b30706705392bee8191dbcb121eb29ccf/src/main.py#L189
You need to augment this on_message to not proceed when your custom commands are identified
